version: 2.1

jobs:
  pr-checks:
    docker:
      - image: cimg/node:18.20
    steps:
      - checkout
      - restore_cache:
          name: Restore cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install
      - save_cache:
          name: Save cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths: [node_modules]
      - run:
          name: Check lint
          command: yarn lint

workflows:
  pr-workflow:
    jobs:
      - pr-checks
